version: 0.2
phases:
  install:
    commands:
      - apk add make nodejs npm
  build:
    commands:
      - make compile
      - make test
  post_build:
    commands:
      - make deploy
cache:
  paths:
    - '/root/.m2/repository/**/*'
