version: 0.2
phases:
  install:
    commands:
      - chmod u+x .cicd/*.sh
  build:
    commands:
      - cd kotlin && mvn clean install
  post_build:
    commands:
      - cd kotlin && mvn deploy
cache:
  paths:
    - '/root/.m2/repository/**/*'
