version: 0.2
phases:
  install:
    commands:
      - apk add make
  build:
    commands:
      - make build
  post_build:
    commands:
      - make deploy
cache:
  paths:
    - '/root/.m2/repository/**/*'
