version: 0.2

env:
  variables:
    MAVEN_CONFIG: "--settings /usr/share/java/maven-3/conf/settings.xml"

phases:
  install:
    commands:
      - apk add make nodejs npm
      - chmod u+x kotlin/mvnw
  build:
    commands:
      - make compile
      - make test
  post_build:
    commands:
      - make deploy
cache:
  paths:
    - '/root/.m2/repository/**/*'
    - '/root/.m2/wrapper/**/*'
    - '/root/.npm/**/*'
    - '/var/cache/apk/**/*'
