version: 1

name: uapi-model-language

pipelines:
  dev:
    phases:
    - type: github
      name: Github
      owner: byu-oit
      repo: uapi-model-language
      branch: master
    - type: codebuild
      name: Build
      build_image: <account>/docker-openjdk-maven
      cache: s3
#    - type: slack_notify
#      name: Notify
#      channel: "#custom-code-bots"
#      message: "Successfully built and deployed uapi-model-language to maven repo"
